-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."posts" add column "onchain_dao_project_id" integer
--  not null;
